import type { Metadata } from "next";
import localFont  from "next/font/local"; //добавляю шрифт
import "./globals.css";
import {TheHeader} from "../components/TheHeader/TheHeader";

const Satoshi = localFont({ src: [{
  path: '../../src/Fonts/Satoshi-Medium.ttf',
    weight: '500'

  },
    {
      path: '../../src/Fonts/Satoshi-Regular.ttf',
      weight: '400'
    }
  ] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={Satoshi.className}>
    <TheHeader></TheHeader>
      <div>
        {children}
      </div>
    </body>
    </html>
  );
}
